# Generated by Django 3.0.7 on 2020-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonbad', '0002_auto_20200627_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
